name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}



jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: action/checkout@v3


    
      - name: Setup Python
        uses: action/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run Python Script
        run:
          python main.py



